ecom/Customers/urls.py
from django.urls import path
from . import views

app_name = 'Customers'

urlpatterns = [
    path('customer_page/', views.customerpage , name='customer_page'),
    path('product/<int:product_id>/action/', views.handle_product_action , name='handle_product_action'),
    path('orderhistory/', views.orderhistory , name='order'),
    path('confirm_orders/', views.confirm_order , name='confirm_order'),
    path('address/', views.address , name='address'),
    path('checkout/', views.checkout , name='checkout'),
    path('cart/', views.cart , name='cart'),
]

ecom/Seller/urls.py
from django.urls import path
from . import views

app_name = 'Seller'

urlpatterns = [
    path('admin_dashboard/', views.admin , name='admin_dashboard'),
    path('add_product/', views.product_add , name='add_product'),

]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('carinterior/',views.carinterior, name='carint'),
    path('carexterior/',views.carexterior, name='carext'),
    path('carcare/' ,views.carcare, name= 'carcare'),
    path('carstyling/' , views.carstyling, name='carstyling'),
    path('bulkdiscount/', views.bulkdiscount, name='bulkdiscount'),
    path('returnpolicy/' , views.returnpolicy, name= 'returnpolicy'),
    path('contactus/', views.contactus, name='contactus' ),
    path('signup/', views.signup, name='signup' ),
    path('login/', views.login, name='login' ),
    path('logout/', views.logout , name='logout'),
    path('seller', include('Seller.urls')),
    path('customer/', include('Customers.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/templates/carcare.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/carcare.css' %}">
    
</head>
<body>
    <!-- navbar started -->
     {% include 'navbar.html' %}

     <section id="background1" style="background-image: url('{% static 'images/banner/carwash1.jpeg' %}');">
        <div id="gearhub">
            <header>
                <h1>Welcome to CarGearHub</h1>
            </header>
            <div class="text">
                <p>"𝔈𝔵𝔭𝔩𝔬𝔯𝔢 𝔬𝔲𝔯 𝔠𝔬𝔪𝔭𝔩𝔢𝔱𝔢 𝔠𝔞𝔯 𝔠𝔞𝔯𝔢 𝔯𝔞𝔫𝔤𝔢, 𝔣𝔢𝔞𝔱𝔲𝔯𝔦𝔫𝔤 𝔥𝔦𝔤𝔥-𝔮𝔲𝔞𝔩𝔦𝔱𝔶 𝔴𝔞𝔵𝔢𝔰, 𝔠𝔩𝔢𝔞𝔫𝔢𝔯𝔰, 𝔞𝔫𝔡 𝔭𝔯𝔬𝔱𝔢𝔠𝔱𝔞𝔫𝔱𝔰 𝔣𝔬𝔯 𝔞 𝔟𝔯𝔦𝔩𝔩𝔦𝔞𝔫𝔱 𝔣𝔦𝔫𝔦𝔰𝔥 𝔞𝔫𝔡 𝔩𝔞𝔰𝔱𝔦𝔫𝔤 𝔭𝔯𝔬𝔱𝔢𝔠𝔱𝔦𝔬𝔫."</p>
            </div>
            <div class="button-container">
                <a href="{% url 'about' %}" class="car-button button1">About us</a>
                <a href="{% url 'carext' %}" class="car-button button2">Car Exterior</a>
            </div>
        </div>
     </section>

    <div id="ground" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        <div id="carinterior1" style="background-image: url('{% static 'images/banner/carcare12.jpg' %}');">
            <div id="carname1" style="color: black;">
                Car Ceramic
            </div>
        </div>
        {% for product in care_product|slice:"0:3" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
    </div>
    
    
    <div id="ground2" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        {% for product in care_product|slice:"3:6" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
        
        
        <div id="carinterior2" style="background-image: url('{% static 'images/banner/carcareimg2.webp' %}');">
            <div id="carname1">
            Car Gloss
            </div>
        </div>
    </div>
    
    <div id="ground" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        <div id="carinterior3" style="background-image: url('{% static 'images/banner/carcareimg1.webp' %}');">
            <div id="carname1" style="background-color: orange; color: aliceblue;">
                Car Shampoo
            </div>
        </div>
        {% for product in care_product|slice:"6:9" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
    </div>
    {% include 'footer.html' %}
    

    
            
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    
</body>

ecom/templates/carexterior.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/carint.css' %}">
    
    <script src="{% static 'js/carext.js' %}"></script>
</head>
<body>
    <!-- navbar started -->
     {% include 'navbar.html' %}

     <section id="background1" style="background-image: url('{% static 'images/banner/hdcarext2.jpg' %}');">
        <div id="gearhub">
            <header>
                <h1>Welcome to CarGearHub</h1>
            </header>
            <div class="text">
                <p>𝔈𝔵𝔭𝔢𝔯𝔦𝔢𝔫𝔠𝔢 𝔲𝔫𝔪𝔞𝔱𝔠𝔥𝔢𝔡 𝔢𝔩𝔢𝔤𝔞𝔫𝔠𝔢 𝔞𝔫𝔡 𝔭𝔢𝔯𝔣𝔬𝔯𝔪𝔞𝔫𝔠𝔢 𝔴𝔦𝔱𝔥 𝔬𝔲𝔯 𝔠𝔞𝔯'𝔰 𝔰𝔱𝔲𝔫𝔫𝔦𝔫𝔤 𝔢𝔵𝔱𝔢𝔯𝔦𝔬𝔯, 𝔠𝔯𝔞𝔣𝔱𝔢𝔡 𝔣𝔬𝔯 𝔱𝔥𝔬𝔰𝔢 𝔴𝔥𝔬 𝔡𝔢𝔪𝔞𝔫𝔡 𝔢𝔵𝔠𝔢𝔩𝔩𝔢𝔫𝔠𝔢.</p>
            </div>
            <div class="button-container">
                <a href="{% url 'home' %}" class="car-button button1">Home</a>
                <a href="{% url 'carint' %}" class="car-button button2">Car interior</a>
            </div>
        </div>
     </section>

    <div id="ground" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        <div id="carinterior1" style="background-image: url('{% static 'images/banner/bodycover1.jpg' %}');">
            <div id="carname1">
                Car BodyCover
            </div>
        </div>
        {% for product in exterior_product|slice:"0:3" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
    </div>
    
    <div id="ground2" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        {% for product in exterior_product|slice:"3:6" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
        <div id="carinterior2" style="background-image: url('{% static 'images/banner/doorguardhd1.webp' %}');">
            <div id="carname1">
                Car DoorGuard
            </div>
        </div>
    </div>
    <div id="ground" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        <div id="carinterior3" style="background-image: url('{% static 'images/banner/wheelcoverhd1.avif' %}');">
            <div id="carname1">
                Car WheelCover
            </div>
        </div>
    
        
        {% for product in exterior_product|slice:"6:9" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
    </div>
        
        
        {% include 'footer.html' %}
    

    
            
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    
</body>

ecom/templates/carinterior.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/carint.css' %}">
    
</head>
<body>
    <!-- navbar started -->
     {% include 'navbar.html' %}

     <section id="background1" style="background-image: url('{% static 'images/banner/hdback3.jpg' %}');">
        <div id="gearhub">
            <header>
                <h1>Welcome to CarGearHub</h1>
            </header>
            <div class="text">
                <p>"𝕰𝖝𝖕𝖊𝖗𝖎𝖊𝖓𝖈𝖊 𝕷𝖚𝖝𝖚𝖗𝖞 𝖆𝖓𝖉 𝕮𝖔𝖒𝖋𝖔𝖗𝖙: 𝕽𝖊𝖉𝖊𝖋𝖎𝖓𝖊 𝖄𝖔𝖚𝖗 𝕯𝖗𝖎𝖛𝖊 𝖜𝖎𝖙𝖍 𝕺𝖚𝖗 𝕻𝖗𝖊𝖒𝖎𝖚𝖒 𝕮𝖆𝖗 𝕴𝖓𝖙𝖊𝖗𝖎𝖔𝖗𝖘"</p>
            </div>
            <div class="button-container">
                <a href="{% url 'home' %}" class="car-button button1">Home</a>
                <a href="{% url 'about' %}" class="car-button button2">About Us</a>
            </div>
        </div>
     </section>

    <div id="ground" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        <div id="carinterior1" style="background-image: url('{% static 'images/banner/hdcarinterior2.jpg' %}');">
            <div id="carname1">
                Car Interior
            </div>
        </div>
        
        {% for product in interior_product|slice:"0:3" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
    </div>

    <div id="ground2" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        {% for product in interior_product|slice:"3:6" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
        <div id="carinterior2" style="background-image: url('{% static 'images/banner/hdfootmat1.jpg' %}');">
            <div id="carname1">
                Car FootMats
            </div>
        </div>
    </div>
    <div id="ground" style="background-image: url('{% static 'images/banner/wall1.jpg' %}');">
        <div id="carinterior3" style="background-image: url('{% static 'images/banner/hdfootmat2.jpg' %}');">
            <div id="carname1">
                Car Cupholders
            </div>
        </div>
        {% for product in interior_product|slice:"6:9" %}
        <div class="card-product1">
            <img src="{{product.product_image.url}}"alt="Product 1">
            <div class="card-content-1">
            <h3 class="card-title-1">{{product.product_name}}</h3>
            <form method="post" action="{% url 'Customers:handle_product_action' product.product_id %}">
            {% csrf_token %}
                <div class="quantity-selector">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="10" class="quantity-input">
                </div>
                <div class="price">Rs {{product.product_price}}</div>
                    <div class="card-buttons">
                        <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
                        <button type="submit" name="action" value="buy_now">Buy Now</button>
                    </div>
                </div>
            </form>
        </div>
        {% endfor %}
        
    </div>
    {% include 'footer.html' %}
    

    
            
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    
</body>

ecom/templates/navbar.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>car access</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    
    
  </head>
  <body>
    
    <nav class="navbar">
        <img src="{% static 'images/banner/brandlogo1.png' %}" alt="Brand Logo" class="brand-logo">
        <ul class="nav-menu">
            <li class="nav-item">
                <a href="#">CAR CARE INTERIOR & EXTERIOR</a>
                <ul class="dropdown">
                    <li><a href="{% url 'carint' %}">Car Interior</a></li>
                    <li><a href="{% url 'carext' %}">Car Exterior</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="#">CAR CARE & STYLING</a>
                <ul class="dropdown">
                    <li><a href="{% url 'carcare'%}">Car Care</a></li>
                    <li><a href="{% url 'carstyling' %}">Car Styling</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{% url 'bulkdiscount' %}">Bulk Discounts</a>
            </li>
            <li class="nav-item"><a href="{% url 'returnpolicy' %}">Return Policy</a></li>
            <li class="nav-item">
                <a href="{% url 'contactus' %}">CONTACT US</a>
            </li>
        </ul>
        <div class="search-bar">
            <input type="text" placeholder="Search...">
        </div>
        <div class="nav-icons">
            <button class="icon-button" onclick="location.href='{% url 'home' %}'"><i class="bi bi-house-gear"></i>
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house-gear" viewBox="0 0 16 16">
                    <path d="M7.293 1.5a1 1 0 0 1 1.414 0L11 3.793V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v3.293l2.354 2.353a.5.5 0 0 1-.708.708L8 2.207l-5 5V13.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 1 0 1h-4A1.5 1.5 0 0 1 2 13.5V8.207l-.646.647a.5.5 0 1 1-.708-.708z"/>
                    <path d="M11.886 9.46c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.044c-.613-.181-.613-1.049 0-1.23l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382zM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
                  </svg>
            </button>
            {% if request.session.customer_id or request.session.admin_id %}
            <div class = "ms-2 bg-primary p-2 rounded">
                {% if request.session.customer_id %}
                <a class="text-white"  href="{% url 'Customers:customer_page' %}">{{request.session.customer_name}}</a>
                {% elif request.session.admin_id %}
                <a class="text-white" href="{% url 'Seller:admin_dashboard' %}">{{request.session.admin_name}}</a>
                {% endif %}
                
              <a class="btn btn-success ms-2" href="{% url 'logout' %}">Logout</a>
            </div>
              {% else %}
              <a type="button" class="btn btn-success" href="{% url 'signup' %}" style="margin-left: 30px;" >SignUp</a>
             <a type="button" class="btn btn-dark" href="{% url 'login' %}" style="margin-left: 30px;">login</a> 
             
              {% endif %}
            
            <button class="icon-button"onclick="location.href='#'" style="margin-left: 15px;"><i class="bi bi-cart4" ></i>
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                  </svg>
            </button>
        </div>
    </nav>

  
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/all.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
  </body>
</html>